services:
  mongodb:
    image: mongo:8
    container_name: civicconnect-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - civicconnect-data:/data/db

volumes:
  civicconnect-data:
